# Generated by Django 5.2.8 on 2025-11-18 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0002_resultsnapshot'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountSession',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=50)),
                ('operador', models.CharField(max_length=100)),
                ('comentario', models.TextField(blank=True, null=True)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-creado_en'],
            },
        ),
        migrations.CreateModel(
            name='LocationBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pn', models.CharField(max_length=50)),
                ('ubicacion', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=255, null=True)),
                ('activo', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['pn', 'ubicacion'],
                'unique_together': {('pn', 'ubicacion')},
            },
        ),
        migrations.CreateModel(
            name='CountDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('revisado', models.BooleanField(default=False)),
                ('fecha_revision', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='app_inventario.countsession')),
                ('base', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conteos', to='app_inventario.locationbase')),
            ],
            options={
                'unique_together': {('session', 'base')},
            },
        ),
    ]
