# Generated by Django 5.0.3 on 2025-11-20 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_inventario', '0003_countsession_locationbase_countdetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='countdetail',
            name='cantidad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
